name: Download Translations

on:
  schedule:
  - cron: "0 2 * * 1-5"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
         command: 'download'
         command_args: '--all'
         token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }} # A Personal Access Token (see https://crowdin.com/settings#api-key)
         project_id: ${{ secrets.CROWDIN_PROJECT_ID }} # The numeric project ID. Visit the Tools > API section in your Crowdin project
